version: '3.3'

services:
  site:
    container_name: rmjs-site
    build: ./site
    env_file: ./site/.env
    ports: 
      - "3000:3000"
    networks:
      - rm-net
  api:
    container_name: rmjs-api
    build: ./server
    environment: 
     - TOKEN={{ADD TOKEN HERE!!!}}
    ports: 
    - "3001:3001"
    networks:
      - rm-net
networks:
  rm-net: